### ISSUE TITLE
Could not execute entrypoint stage 'main'

### ISSUE THREAD

**Issue by AlexisBloodwood** [GabrielOlvH/WirelessNetworks#1]
Wanted to use the mod to lower the amount of cables running through my base when I ended up with the following crash log :(

Crash Log: [Sadness](https://0bin.net/paste/EGhTWcT6#svTAQVL18O25K7pDUCEdzR832n3oQmSsKd+Rl5w+38B)

**Comment by GabrielOlvH** [comment]
Update Fabric API

**Comment by AlexisBloodwood** [comment]
My Fabric API is at 0.30.0, does it need to be higher than that?

**Comment by RemagOfficial** [comment]
use the latest one, theres no reason not to

**Comment by AlexisBloodwood** [comment]
Ah, just loaded it up, I was afraid some of my other mods wouldn't work with the API update as it had happened in the past. Thank you!
