### ISSUE TITLE
Network Node won't output to MI Machines

### ISSUE THREAD

**Issue by Frankiscophil** [GabrielOlvH/WirelessNetworks#10]
I found this mod through a tutorial by Niche Duck on Youtube showcasing how the Wireless Node can connect and power up Modern Industrialization machines. Upon looking through, it seems that specific feature no longer works in the newer versions of that mod. All in all, I wanted to ask if a future version of this awesome mod will be able to bypass that restriction in Modern Industrialization.

**Comment by GabrielOlvH** [comment]
MI doen't accept energy from other mods by design, you can try asking them to allow receiving energy from the nodes but I won't bypass their mechanic
