### ISSUE TITLE
Networks seem to be input only

### ISSUE THREAD

**Issue by snowboundmage2** [GabrielOlvH/WirelessNetworks#5]
can easily put energy into a network, but cant pull any out
yes they are both connected to the same network
tried putting new ones down, new networks, different cables(IR and MI), different input/output/storage numbers
1.17.1 minecraft
1.1.2 Wireless networks

**Comment by GabrielOlvH** [comment]
Can you send screenshots of your setup?

**Comment by snowboundmage2** [comment]
![2021-07-22_21 14 47](https://user-images.githubusercontent.com/85192202/126631252-5253c864-a95d-4634-82c8-99392e7272ee.png)

**Comment by Tatitooo** [comment]
I'm having the same issue.

**Comment by MathiasDeWeerdt** [comment]
Its a problem with the new version of industrial revolution try another mod for cabling.

**Comment by GabrielOlvH** [comment]
The problem is actuallly here, the indrev update just exposed the problem. A new update should be coming out soon to fix it.

**Comment by MathiasDeWeerdt** [comment]
> The problem is actuallly here, the indrev update just exposed the problem. A new update should be coming out soon to fix it.

ah, cool. Hope its an easy fix. Btw thanks for the mod, I really like it!
