### ISSUE TITLE
Bug on 1.1.2

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [GabrielOlvH/WirelessNetworks#6]
![image](https://user-images.githubusercontent.com/7256303/127231076-0c307b2b-cfa3-4aac-9482-2d5717dbc1b9.png)

Transferring power like this used to work perfectly fine on version 1.1.1. But it doesnt anymore on version 1.1.2.
Code on github isnt up-to-date, so I couldnt check it out, wouldve looked for it ;)

**Comment by MathiasDeWeerdt** [comment]
Seems like the problem is industrial revolution and not Wireless Networks. Sorry, my bad.

**Comment by GabrielOlvH** [comment]
The problem is actuallly here, the indrev update just exposed the problem. A new update should be coming out soon to fix it.
