### ISSUE TITLE
Crash after updating Fabric API to 0.38.0 (probably)

### ISSUE THREAD

**Issue by mtb-xt** [GabrielOlvH/WirelessNetworks#9]
Hi, the mod crashes after updating Fabric API to 0.38.0.

See attached log - https://paste.atlauncher.com/view/2f0766f4-15b6-44b8-a63a-1e2575996baf  

The error is not very descriptive, but I went and disabled\enabled all mods one by one until I found that it's Wireless Networks that crashes... :eyes:

**Comment by itsdinkd** [comment]
it doesn't allow any update of fabric API past .72 

went through 160+ mods of my modpack one by one disabling them and this is the culprit.
